src/Entity/TeacherSchedule.php
<?php

namespace App\Entity;

use App\Repository\TeacherScheduleRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TeacherScheduleRepository::class)]
class TeacherSchedule
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $day_number = null;

    #[ORM\Column]
    private ?int $hour_number = null;

    #[ORM\Column(length: 10, nullable: true)]
    private ?string $subject_abbreviation = null;

    #[ORM\Column(length: 30)]
    private ?string $subject = null;

    #[ORM\Column(length: 50)]
    private ?string $teacher_name = null;

    #[ORM\Column(length: 50)]
    private ?string $classroom_name = null;

    #[ORM\Column(length: 50)]
    private ?string $group_name = null;

    #[ORM\Column(length: 5)]
    private ?string $start_hour = null;

    #[ORM\Column(length: 5)]
    private ?string $end_hour = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDayNumber(): ?int
    {
        return $this->day_number;
    }

    public function setDayNumber(int $day_number): static
    {
        $this->day_number = $day_number;

        return $this;
    }

    public function getHourNumber(): ?int
    {
        return $this->hour_number;
    }

    public function setHourNumber(int $hour_number): static
    {
        $this->hour_number = $hour_number;

        return $this;
    }

    public function getSubjectAbbreviation(): ?string
    {
        return $this->subject_abbreviation;
    }

    public function setSubjectAbbreviation(?string $subject_abbreviation): static
    {
        $this->subject_abbreviation = $subject_abbreviation;

        return $this;
    }

    public function getSubject(): ?string
    {
        return $this->subject;
    }

    public function setSubject(string $subject): static
    {
        $this->subject = $subject;

        return $this;
    }

    public function getTeacherName(): ?string
    {
        return $this->teacher_name;
    }

    public function setTeacherName(string $teacher_name): static
    {
        $this->teacher_name = $teacher_name;

        return $this;
    }

    public function getClassroomName(): ?string
    {
        return $this->classroom_name;
    }

    public function setClassroomName(string $classroom_name): static
    {
        $this->classroom_name = $classroom_name;

        return $this;
    }

    public function getGroupName(): ?string
    {
        return $this->group_name;
    }

    public function setGroupName(string $group_name): static
    {
        $this->group_name = $group_name;

        return $this;
    }

    public function getStartHour(): ?string
    {
        return $this->start_hour;
    }

    public function setStartHour(string $start_hour): static
    {
        $this->start_hour = $start_hour;

        return $this;
    }

    public function getEndHour(): ?string
    {
        return $this->end_hour;
    }

    public function setEndHour(string $end_hour): static
    {
        $this->end_hour = $end_hour;

        return $this;
    }
}

src/Controller/TeacherScheduleController.php
<?php

namespace App\Controller;

use App\Entity\Session;
use App\Entity\Teacher;
use App\Entity\TeacherSchedule;
use App\Service\SessionService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class TeacherScheduleController extends AbstractController
{
    public function index(Request $request, SessionService $session, EntityManagerInterface $entityManager): Response
    {
        $username = $session->get('username');

        $user = $entityManager->getRepository(Session::class)->findOneBy(['username' => $username]);

        $teacher = $user->getTeacher()->getEmploye();

        $schedule = $entityManager->getRepository(TeacherSchedule::class)->findBy(['teacher_name' => $teacher]);

        return $this->render('teacher_schedule/index.html.twig', [
            'schedule' => $schedule
        ]);
    }
}

templates/teacher_schedule/partials/teacherSchedule.html.twig
{% set daysOfWeek = ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes'] %}
{% set hoursOfDay = [
    '8:30', 
    '9:30', 
    '10:30',
    '10:50', 
    '11:50',
    '12:50', 
    '13:00', 
    '14:00', 
    '15:00', 
    '15:30', 
    '16:30', 
    '17:30', 
    '17:45',
    '18:45', 
    '19:45', 
    '20:00', 
    '21:00'
    ] %}

<div class="relative overflow-x-auto shadow-md sm:rounded-lg w-100">
	<table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400 text-center">
		<thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
			<tr>
				<th scope="col" class="px-6 py-3">
					Día
				</th>
				<th scope="col" class="px-6 py-3">
					Hora
				</th>
				<th scope="col" class="px-6 py-3">
					Abreviatura
				</th>
				<th scope="col" class="px-6 py-3">
					Asignatura
				</th>
				<th scope="col" class="px-6 py-3">
					Aula
				</th>
				<th scope="col" class="px-6 py-3">
					Grupo
				</th>
				<th scope="col" class="px-6 py-3">
					Comienzo
				</th>
				<th scope="col" class="px-6 py-3">
					Finalización
				</th>
			</tr>
		</thead>
		<tbody>
			{% for day in schedule %}
				<tr class="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b dark:border-gray-700">
					<th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
						{{daysOfWeek[day.dayNumber - 1]}}
					</th>
					<td class="px-6 py-4">
						{{hoursOfDay[day.hourNumber - 1]}}
					</td>
					<td class="px-6 py-4">
						{{day.subjectAbbreviation}}
					</td>
					<td class="px-6 py-4">
						{{day.subject}}
					</td>
					<td class="px-6 py-4">
						{{day.classroomName}}
					</td>
                    <td class="px-6 py-4">
						{{day.groupName}}
					</td>
                    <td class="px-6 py-4">
						{{day.startHour}}
					</td>
                    <td class="px-6 py-4">
						{{day.endHour}}
					</td>
				</tr>
			{% endfor %}
		</tbody>